### PR TITLE
Fix stripHash function to allow for URL query params

### PR DESCRIPTION
**Pull request by Sacharified**
This issue currently causes some severe playback issues if you have query params in your page URL.

When a `mediaNode` attempts to `get` a media element from the `VideoElementCache`, the `get` method checks to see if the element has already been assigned a source.

There is a strange behaviour in the browser where the `src` property of the element is sometimes set to the current page's URL, so the method checks to see if the `src` is the same as the current page URL, sans the `hash` (as this can change without reloading the page).

Due to the query params not being included in the returned value of `stripHash`, this comparison will never return true if the current URL has query params, so `get` will never return the element as intended.

### CODE REVIEW

**Comment by PTaylour** [comment]
Wow that it interesting.

HTMLMediaElement spec says that `src` must be "a valid URL but it is not the empty string."

`document.createElement("video").src` gives `""` so it's not like it defaults to `""`

However if you set it to `""`

```
let a = document.createElement("video")
13:51:23.498 undefined
13:51:25.665 a.src
13:51:25.670 ""
13:51:30.107 a.src = ""
13:51:30.110 ""
13:51:33.152 a.src
13:51:33.155 "https://github.com/bbc/VideoContext/pull/104"
```

chrome makes sure it is valid by setting it to the current location (it seems)

**Comment by PTaylour** [comment]
```
let b = document.createElement("video")
13:54:44.903 undefined
13:54:48.747 b.src
13:54:48.751 ""
13:54:53.074 b.src = undefined
13:54:53.078 undefined
13:54:53.075 104:1 Refused to load media from 'https://github.com/bbc/VideoContext/pull/undefined' because it violates the following Content Security Policy directive: "media-src 'none'".
```

So if you don't give it a valid url it assumes you're doing a relative path

**Comment by PTaylour** [comment]
So this line is a bug really

https://github.com/bbc/VideoContext/blob/1e04ea6679f22d51cc2d2ec1ce2fea3ed11d6725/src/videoelementcache.js#L24

**Comment by Sacharified** [comment]
> So this line is a bug really
> 
> [VideoContext/src/videoelementcache.js](https://github.com/bbc/VideoContext/blob/1e04ea6679f22d51cc2d2ec1ce2fea3ed11d6725/src/videoelementcache.js#L24)
> 
> Line 24 in [1e04ea6](/bbc/VideoContext/commit/1e04ea6679f22d51cc2d2ec1ce2fea3ed11d6725)
> 
>  videoElement.src = "";

Good shout, I've pushed an update which removes the workaround and prevents the erroneous `src` from being set. I've also changed the `unload` method to follow the best practice for "unloading" video elements as defined [here](https://html.spec.whatwg.org/multipage/media.html#best-practices-for-authors-using-media-elements).

**Comment by PTaylour** [comment]
That's fantastic, thanks!

**Pull request merged**
