### PR TITLE
Improve cross fade transition for video

### PR DESCRIPTION
**Pull request by gsouquet**
Hi,

Given two video node defined as followed: 

```
const videoNode1 = vc.video("one.mp4"); // one.mp4 is 10 seconds long
const videoNode2 = vc.video("two.mp4", -2); // two.mp4 is 20 seconds long

videoNode1.start(0)
videoNode1.stop(12);

videoNode2.start(8);
videoNode2.stop(28);
```

Now we can add a cross fade transition defined as followed

```
const ecf = vc.transition(VideoContext.DEFINITIONS.CROSSFADE);
ecf.transition(8, 12, 0, 1, "mix");
```

From time 8 to 10 `videoNode2` will hold the first frame because there is no video content available.
From time 10 to 12 `videoNode1` will hold the last frame because it is past its duration.

If you seek forward from 8 to 12 you will see the frame being held correctly. However, if you seek past the end of the transition and you start seeking backward, when land on a time lower than 12, `videoNode2` will not change its state because it relies on the actual video element state.

I have created a gist to showcase the behaviour update I did: https://gist.github.com/gsouquet/ad54102ca38d8a3979fdf241e1427ca1

### CODE REVIEW

**Comment by PTaylour** [comment]
Looks good. I'm just trying to get my head around how this is working.

Before, the source node class monitored the state of the actual HTMLElement and ensured that the class state `this._state` was kept up to date, and callbacks fired.

In both versions setting the internal state to `SOURCENODESTATE.ended` pauses the element https://github.com/bbc/VideoContext/pull/137/files#L259-L263

In the old version is `if (this._element.ended)` only true if the user ends the element? Or does another part of the code set this?

Does the new version have any problems if the user pauses the element?

**Comment by PTaylour** [comment]
@gsouquet do you have an insight on this?

**Comment by gsouquet** [comment]
Apologies, I forgot to reply on this one.

You are correct, right now we monitor the state of the `HTMLElement`. However, digging a bit into that problem it looks like there's no real need for that and we might actually benefit from not listening to the DOM element state.

The callbacks are now fired when the VC `_currentTime` goes beyond the media node `_endTime`. So far with our testing we haven't found any problems when pausing.
We don't need to rely on `this._element.ended` at all. Setting the media node state to `ended` means that the updatable manager will not include that node during the compositing phase. On the other hand, if the actual media is ended, it will display the last frame frozen and because the node is still marked as playing the updatable manager will continue to paint it.

However I want to write a whole set of regression tests to really document that scenario as it could be easy to break that behaviour in the future.

When I was doing some more testing I found a specific use case that needs to be fixed when we need to freeze the first frame. I aim to push that shortly with a set of tests.

What do you think of that behaviour? It seems to be aligned with what the Adobe suite of Final Cut Pro do for transitions.

**Comment by PTaylour** [comment]
> What do you think of that behaviour? It seems to be aligned with what the Adobe suite of Final Cut Pro do for transitions.

Seems reasonable!


> When I was doing some more testing I found a specific use case that needs to be fixed when we need to freeze the first frame. I aim to push that shortly with a set of tests.

If this is to be a breaking change, it would be really useful to write a migration guide for examples like this.


> However I want to write a whole set of regression tests to really document that scenario as it could be easy to break that behaviour in the future.


That sounds great

**Pull request closed without merging**
