### PR TITLE
Clean up tooling and project structure

### PR DESCRIPTION
**Pull request by gsouquet**
Small PR around tooling and dependencies

- Clean up unused dependencies
- Upgrade all dependencies
- Clean up our babel configuration
- Removed unused webpack configuration

Things that I tried to do that didn't work:

- Upgrade babel to version 7. The reason is that jest internals is still using `babel-core@6`. It has some version clash. When `jest@24` is out of beta we will be able to upgrade the babel version up.

### CODE REVIEW

**Comment by PTaylour** [comment]
image

50% pixels off, could be outputting just black frames.

It also could just be the regression tests being flaking. I'm rerunning them now

**Comment by gsouquet** [comment]
I dug a bit into why the CI build was failing.

It turns out that the babel plugin `babel-plugin-add-module-exports` is needed.

There is probably a better way to load the scripts in the regression HTML pages but I have not taken the time to properly look into that. That's going to be for another PR in the future.

All regression tests are green on my local machine. I'm a bit unsure why Travis is still complaining here.

I added another commit to change the documentation to refer to `yarn` over `npm`. Because in the PR #83 it seems that it has been decided that we should switch to that tool.

FYI there are no travis deploy provider for yarn. Hence why I kept the `npm` reference in the `.travis.yml` file.

Let me know if you have any more questions, but I feel like this should good to go 👍

**Comment by PTaylour** [comment]
strange, I'll try updating the branch as it's out of date

**Comment by PTaylour** [comment]
`yarn run test-regression` is failing locally for me

**Comment by PTaylour** [comment]
We've been using cypress internally. Should be a pretty quick job to switch to that. Would give us better visibility of which 52% of the pixels are different

**Comment by PTaylour** [comment]
I'm going to running the tests with cypress today

**Comment by PTaylour** [comment]
Getting there:

image

**Comment by PTaylour** [comment]
FYI this PR is still blocked by https://github.com/bbc/VideoContext/pull/147, which is still a work in progress. I'll update this branch once 147 is in

**Comment by yakca** [comment]
Closing this in favour of https://github.com/bbc/VideoContext/pull/187 which includes the commits from this PR and resolves the merge conflict. Thanks @gsouquet

**Pull request closed without merging**
