### PR TITLE
Make webpack build mode 'development' when not running in CI pipeline

### PR DESCRIPTION
**Pull request by gsouquet**
This PR aims to speed up the webpack build time when not running in a CI environment.

The mode `production` does a lot of great optimisation. However this comes at a cost... "time". Those optimisations are pretty much useless for development.

Environment variables config are set in the `.travis.yml` file.

- [webpack mode doc](https://webpack.js.org/concepts/mode/)
- [Travis env var doc](https://docs.travis-ci.com/user/environment-variables/)

I've also updated the ESLint config so that it is enabled but also acknowledges that this files runs in a node environment with its own set of global variables.

Couldn't test this against the Travis Pipeline but I'm fairly confident that it should work 👍

### CODE REVIEW

**Comment by gsouquet** [comment]
I am wondering, do you know where `webpack.commonjs2.config.js` is used?
I have the feeling that this is never used... but just want to double check before I can delete it

**Comment by PTaylour** [comment]
> I am wondering, do you know where webpack.commonjs2.config.js is used?
I don't think it is. Looks safe to delete

**Comment by gsouquet** [comment]
The build was failing because I misread the Travis documentation! This is now fix and should be passing all fine!
Each line in the `env` will trigger a build. And for the `build` step we need two environment variables, `TEST_SUITE` and `NODE_ENV`. My latest commit fixes that

I have deleted `webpack.commonjs2.config.js` as part of #140

**Comment by PTaylour** [comment]
Looks like it's breaking the TEST_SUIT env variable. 

The `test.sh` script is saying:

> exit 1. TEST_SUITE env should be set to unit, integration or regression


Maybe it's setting it to `build NODE_ENV=production`

**Comment by gsouquet** [comment]
I'm very confused about this because if you look at the travis config that is being applied https://travis-ci.org/bbc/VideoContext/builds/482417790/config

It does not match with the diff of that file in the current PR...

Should I re-open a PR 🤔 ?

**Comment by PTaylour** [comment]
This one looks more up to date https://travis-ci.org/bbc/VideoContext/jobs/488508070/config

And it's failing for a different reason

```
> videocontext@0.52.12 lint /home/travis/build/bbc/VideoContext
> eslint '{src,test}/**/*.js'
sh: 1: eslint: not found
```

**Comment by PTaylour** [comment]
which does look like a problem our end

https://stackoverflow.com/questions/38083622/why-travis-ci-no-run-npm-install-in-node-env-production

**Pull request merged**
